### ISSUE TITLE
Open sourcing Ravio OTP

### ISSUE THREAD

**Issue by gitdev-bash** [raivo-otp/ios-application#119]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would love to see Ravio OTP open sourced under an Open Source License.

**Describe alternatives you've considered**
Other OTP apps

**Additional context**
The current license does not allow for forking, modifying or even sharing the code with others. These properties make it impossible to legally call this app open source.This contradicts with the statement in the Features category In the README.

**Comment by tijme** [comment]
It depends on your definition of open source. The source is available for everyone, but unfortunately redistribution is not allowed. I had to do this because people started redistributing my app in the Apple App Store for commercial purposes. This introduces legal issues for me as redistribution is not allowed in the Apple App Store.

If you want to use the source, let me know for what and I'll probably approve :)
