### ISSUE TITLE
Please allow hiding the "previous token" in options.

### ISSUE THREAD

**Issue by KuJoe** [raivo-otp/ios-application#125]
**Is your feature request related to a problem? Please describe.**
Having a bunch of numbers on the screen is a distracting with my poor eyesight.

**Describe the solution you'd like**
Removing any excess numbers would be very helpful. Adding an option to hide the previous token from the list and centering the current token would be much easier to read.

**Describe alternatives you've considered**
Removing/hiding the previous token would be ideal, but if not an option then increasing the font size of the tokens might be a viable alternative.

**Comment by timskkim** [comment]
@KuJoe Thanks for the great suggestion! I've created a PR (#126) implementing this feature, ready for review by any maintainers.

**Comment by jfreedman0** [comment]
In the same realm of this is the request to show the NEXT rather than the PREVIOUS token. The 2FAS app has this and it's really nice. I'm not sure what the purpose would be of having the PREVIOUS token for an extra 30 seconds. It would make more sense to have the NEXT one available as the time for the current one runs out.

**Comment by timskkim** [comment]
@jfreedman0  could you please help me understand the value of the next token? Is it the extra leeway of input time it provides? Or having two valid codes to use? If it is the two valid codes, in what context are two codes usually helpful?

**Comment by jfreedman0** [comment]
@timskkim it's the former. The leeway that when there is only a couple of seconds left on the current code, by the time you type it into the 2FA box on the site you're on, it has expired and the next code is necessary.

**Comment by timskkim** [comment]
@jfreedman0 got it, that definitely makes sense! Thanks for the explanation. I think this will be easier to implement with a transition to SwiftUI for the list and cells; it would probably be more intuitive to place the next token before the current one (like the previous token was placed after the current one), and dynamically styling the cells for these cases would be a lot easier with that framework

**Comment by jfreedman0** [comment]
@timskkim so I experimented a little bit more because I always thought it was odd that the previous token was still showing, but it turns out that that in most implementations of TOTP, the code doesn't expire at exactly 30 seconds, there's a little bit of buffer built in to handle latency.

So the idea of adding the "next" token and keeping the "previous" token actually are for the same purpose, and leaving the current "previous" token implementation works fine.

The situation is when the current code is about to expire as I'm logging in. If there's only 2 or 3 seconds left to type it in, I thought I might miss the window, but in reality, that token is stil valid for another ~30 seconds or so.

**Comment by tijme** [comment]
I've merged the pull request of @timskkim and it will be published within a few weeks. Thanks a lot 🚀
