### ISSUE TITLE
Amazon logo in icon repository visually flawed

### ISSUE THREAD

**Issue by jamalmarri** [raivo-otp/ios-application#130]
**Describe the bug**
The Amazon logo stored in the Raivo icon repository has a flaw in the “a” shape towards the bottom left. There’s a slight breakage in the curve. This is most easily noticed when the icon svg is viewed in full screen.

**To Reproduce**
1. Create new OTP
2. Select Amazon icon from repository
3. Notice flaw in icon

**Expected behavior**
The icon is unflawed, much unlike the company it represents.

**Screenshots**
![BDE7BD0A-E891-4FFF-9E63-83484626F54F](https://user-images.githubusercontent.com/43688247/170935833-7a2324f9-f3f5-499b-b1f7-f471e7dc8007.jpeg)

**Smartphone:**
 - Device: iPhone 13 Pro
 - OS: iOS 15.5
 - Version 1.3.3 (build-59)

**Additional context**
Ironically enough, I only noticed this issue after seeing that the Amazon logo was used as an example of a best practice icon in the repository contribution instructions.

**Comment by divarre** [comment]
@jamalmarri This would actually need to be fixed in https://github.com/raivo-otp/issuer-icons/tree/master/vectors/amazon.com and not the app itself.

I see someone recently submitted an updated logo for Amazon: https://github.com/raivo-otp/issuer-icons/pull/397 — the black "a" and yellow smile/arrow seems to be Amazon's current logo (and not all yellow as the old logo).

So this will be fixed next time the logos are merged.

**Comment by jamalmarri** [comment]
> @jamalmarri This would actually need to be fixed in https://github.com/raivo-otp/issuer-icons/tree/master/vectors/amazon.com and not the app itself.

My apologies. I knew this issue really belonged in the icons repository, but I couldn’t see an issue section and didn’t want to open a PR without anything to contribute. Shall I close this now, or is there a way to link this issue to be closed with the pull request merging in the icon repository?
