### ISSUE TITLE
Unable to link to Macos

### ISSUE THREAD

**Issue by cocosboss** [raivo-otp/ios-application#165]
I am unable to link iOS app to my MacBook Pro. I scan on my iPhone the QR code from my Mac, nothing gets displayed on my Mac. Deleted the linked device from my Mac many times, reinstalled the MacOS app on my Mac, same thing.
Cannot find any missing permissions in the System references to enable to Raivo.

**Comment by tijme** [comment]
Did you enable notifications for Raivo? Otherwise the notifications will not display.

After linking the two, whenever you tap a password in the iOS app, the password should be copied to the clipboard of your Mac, and you should get a notification.

**Comment by cocosboss** [comment]
Yes, notifications are enabled for Raivo... simply the program behaves like no connection to IOS is done. In IOS I do see the link to MacBook Pro though... not sure what ease to do.... Each time I open Raivo on MacBook is like it's new... with getting started message, QR code and no codes from IOS are displayed in MacBook

**Comment by tijme** [comment]
Are you aware that the MacOS app is not a fully fledged application? It's just a receiver. That the app will stay in the same state is expected behaviour for now.

The only thing you'll notice is that, upon tapping a password in the iOS app, it will be copied to the clipboard of your MacOS application.

So nothing is copied to your clipboard after tapping a password in Raivo for iOS? And another question, what does Raivo OTP for iOS show you when you tap an OTP? Does it state it copied to OTP to your Mac?

**Comment by cocosboss** [comment]
Yeah, it is quite strange... after several re-installs and enabling notifications it worked, then after a reboot it stopped working. Now it is working again.
Yes, I was aware I just get a notification in macOS with the code being saved in clipboard and not generated in the macOS app. Hope this time will not stop working :) thanks for all your support!
