### ISSUE TITLE
Don't delete items right away - put them in a "trash" for some time.

### ISSUE THREAD

**Issue by igr** [raivo-otp/ios-application#185]
When you have many items, its easy to make a mistake. We are humans, after all :)

It would be great if I can restore deleted item.

**Comment by Pimi831** [comment]
A pop-up indicating if they are sure they want to delete the account and notifying them that the action cannot be undone would be great. This is how it's done with Google Authenticator, with Raivo it's really easy to accidentally click on delete.

**Comment by xuhu55** [comment]
I think putting them in the trash is a security risk if a bad actor can access them. If you delete them you probably want them gone permanently but the confirmation feature is a good solution.

**Comment by LawHoo** [comment]
I think a Recycle Bin / Recently Deleted concept makes sense. People probably are only very rarely deleting entries from Raivo OTP for security concerns (e.g., "I don't want this particular entry in Raivo OTP any more because I think someone might get their hands on my Raivo OTP app/data."). I think the more usual situation--at least for me--is deleting old OTP entries that are no longer used (e.g., closed accounts, accounts where I switched to hardware security keys, etc.). So it would be helpful to have the ability to recover an OTP entry if I accidentally deleted the wrong one. .... BUT, maintaining backups does mitigate that risk too.
