### ISSUE TITLE
Add 2FA to the end of the name as I can't seem to ever remember the name of the app but I know what it does. If you add 2FA to the end it would be easier to search and remember. Raivo 2FA. Thanks for the great app.

### ISSUE THREAD

**Issue by heavyMGS** [raivo-otp/ios-application#188]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tijme** [comment]
Hello @heavyMGS,

I've thought about this for a while and have decided not to add 2FA behind the name, especially because users search for different terms such as 2FA, MFA or OTP. I want to keep it clean and simple and I hope that I can somehow add keywords to the app so that it shows up in iOS search results as soon as you search for one of these terms. Additionally, I hope to implement autofill of OTP tokens which is requested in another feature requests, so the app does not have to bee opened often.
