### ISSUE TITLE
Icon repository not working

### ISSUE THREAD

**Issue by benzo83** [raivo-otp/ios-application#20]
**Describe the bug**
I find impossible to download icons from the repository, I always get this error: "Update Failed - An SSL error has occurred and a secure connection to the server cannot be made."
I tried with WiFi, data connection or vpn and I get always the same error.

**Screenshots**
![image](https://user-images.githubusercontent.com/64498014/89719604-5facc200-d9ca-11ea-9ce2-99642a29f36b.png)
![image](https://user-images.githubusercontent.com/64498014/89719630-8965e900-d9ca-11ea-8976-727ff1062421.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 13.6
 - Version 1.1.10 (build-29)

**Comment by tijme** [comment]
Hey @benzo83,

This should be fixed now.Apparently the domain where the icons are hosted had an invalid TLS certificate (expired). This was due to the fact that the LetsEncrypt Certbot couldn't update the certificate. Apparently it's because of a bug in the version of the Certbot that i'm using. See [this issue](https://community.letsencrypt.org/t/auto-renewal-started-failing-with-error-missing-command-line-flag-or-config-entry-for-this-setting/111211) for more information.

Thanks for reporting!
