### ISSUE TITLE
Restore from (import) ZIP-archive backup/export

### ISSUE THREAD

**Issue by DomBot1** [raivo-otp/ios-application#22]
**Is your feature request related to a problem? Please describe.**
My problem is that I see an option to export the data but I cannot import them (which would come in handy e.g. when migrating to a new phone).

**Describe the solution you'd like**
An option to import the exported data. Something like "Import OTPs from ZIP archive" or whatever would work.

**Describe alternatives you've considered**
Using the sync option but I don't want to store sensitive 2FA data in the cloud. Also I don't even know if this feature would solve my problem as I have (obviously) never used it.

**Additional context**
This feature might also be compatible with other 2FA apps that have an option to import & export 2FA data.

**Comment by KissesRefined** [comment]
@tijme Hey! Any plans to implement this? If not, could you please add to the README instructions for changing phone in general. I assume export has some value / role in the process.

**Comment by tijme** [comment]
Yes, I want to implement this in the future, when I have the time.

Currently you can use the export function to change phone. Extract the zip and open the HTML file. You'll see all the QR-codes that you can scan on your new phone.

**Comment by KissesRefined** [comment]
> Currently you can use the export function to change phone. Extract the zip and open the HTML file. You'll see all the QR-codes that you can scan on your new phone.

I obviously have no idea how this works, but this sounds pretty damn straight forward.

**Comment by skupfer** [comment]
Due to this issue where raivo crashes on adding new tokens https://github.com/raivo-otp/ios-application/issues/69 I had to sign out of Raivo (and luckily made a backup before because there is no sign in for local dbs. this is where I would have expected to be asked for a backup file).

Import functionality is really needed.

**Comment by zer0man98** [comment]
+1
Import functionality would go hand in hand with the backup feature.
Importing from other OTP apps can be a separate feature addition for later, but importing Raivo's own backup should be there.
Allow selecting "raivo-otp-export.zip" from files app and ask for previous master password to decrypt.

**Comment by Mohammad-Kabajah** [comment]
+1 
adding an option to import from the exported data would be great option to give the ability to switch between devices if needed without the need to re-scan all of the accounts manually again since not everyone is like to save this sensitive data on the cloud. Also might be very nice and cool feature if there is an option to sync with local server like a local SFTP, NAS or any locally hosted storage alternative.

**Comment by alonbl** [comment]
I was very surprised too to find an application that supports backup but not restore... :)
Please support.

**Comment by tijme** [comment]
Will be pushed to TestFlight within several days. After several weeks it will be released.
