### ISSUE TITLE
Show iCloud account email

### ISSUE THREAD

**Issue by alexkwa** [raivo-otp/ios-application#26]
**Is your feature request related to a problem? Please describe.**
Some have multiple iCloud account. Since the account email is not shown in the Settings, I have to check if the right iCloud account is synced to.

**Describe the solution you'd like**
Instead of `Personal iCloud`, it should show the email of the iCloud account connected.

**Describe alternatives you've considered**
Another way is to show the email when `Personal iCloud` is tapped on and allow users to go to the relevant iOS setting page.

PS: I am a UX designer. Please don't hesitate if you need a simple prototype. I can provide them if you provide me access to your design files.

**Comment by tijme** [comment]
What a great idea @alexkwa. I totally agree on it. I hope to find some time in my holidays to work on this.

And thanks for using the Feature Request template for creating your issue!

**Comment by alexkwa** [comment]
No worries. Btw, I migrated to your app after Google Authenticator and Tofu. It's the best open source, privacy focused one out there.

**Comment by tijme** [comment]
I've looked into this but it turns out receiving the email address that is linked to a specific CloudKit container is very buggy. Even after requesting permissions and using the default CloudKit container, I can only get the full name of the iCloud user. I've rethought the fix and decided to add some extra context to the description below the settings. This should make it easier for users to find out where to find which account is in use. Will be released in version 1.1.13 (this will be tested in TestFlight first).
