### ISSUE TITLE
Force stock keyboard

### ISSUE THREAD

**Issue by DomBot1** [raivo-otp/ios-application#27]
**Is your feature request related to a problem? Please describe.**
I feel like it would be better for security if the stock iOS keyboard was used throughout the app (e.g. the Secret/Seed textfield).

**Describe the solution you'd like**
Forcing stock keyboard (like iOS does when typing in a password etc.)

**Comment by tijme** [comment]
This will be released in version 1.1.14.

I decided to disable third party keyboards throughout the entire application. It's a rigorous decision, but I don't see any other solution. If I would only apply it to the 'seeds', then I would have to use '[isSecureTextEntry](https://developer.apple.com/documentation/uikit/uitextinputtraits/1624427-issecuretextentry)'. This immediately replaces the seed with bullets, which is quite inconvenient since you want to see the seed.

If you have a different solution, do not hesitate to describe this solution and reopen the issue.
