### ISSUE TITLE
Unable to purchase subscription 

### ISSUE THREAD

**Issue by VintageGenetics** [raivo-otp/ios-application#366]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 11

**Additional context**

**Comment by mobime-org** [comment]
Hello,

We have temporarily blocked subscriptions for Raivo in order to be fair to our loyal previous users. We are currently rolling out an update that will allow old users to fully access Raivo without the need for a subscription. We are just waiting for it to be available in the app store.

Thank you.
