### ISSUE TITLE
Database Emails never arrive?

### ISSUE THREAD

**Issue by HighOnBuffs** [raivo-otp/ios-application#40]
Hi i tried to send my encrypted database per mail (what is used to send the mail?) and i didn't receive an email even though i send it out multiple times?

Also what does the second number in grey mean? I assumed it was the next code after the active one but the next code if completely different?

Also i mistyped my pin code once and it told me 5 tries left? Is everything deleted afterwards?

I like the app and switched from Authy for it but i hope the app is secure and sound!

**Comment by tijme** [comment]
Hi @HighOnBuffs 

> Hi i tried to send my encrypted database per mail (what is used to send the mail?) and i didn't receive an email even though i send it out multiple times?

The primary account in your Apple Mail app is used to send the mail. If you didn't receive the mail, it might be due to your mail provider not allowing attachments of this size/type. In one of the upcoming releases of Raivo the exports can be exported to your local device. This is tracked in feature request #24.

> Also what does the second number in grey mean? I assumed it was the next code after the active one but the next code if completely different?

The second/grey number is the previous OTP token. OTP's mostly change every 30 seconds. But they are valid for a longer time in most cases (around 60 seconds). Therefore, if you started typing an OTP, and a new OTP is shown, you can still continue typing the old OTP (showed in grey) to complete your 2FA sign-in.

> Also i mistyped my pin code once and it told me 5 tries left? Is everything deleted afterwards?
You'll have to wait 60 seconds before retrying again.
> I like the app and switched from Authy for it but i hope the app is secure and sound!

I hope so too! 😄 😄 😄
