### ISSUE TITLE
Remove the Search Button at bottom.

### ISSUE THREAD

**Issue by shane-anderson** [raivo-otp/ios-application#61]
**Is your feature request related to a problem? Please describe.**
It isn't really a problem, more of just a request.

**Describe the solution you'd like**
the app has 3 icons at the bottom. Passwords, Search, and Settings. Given that we already have a search box at the top of the Passwords menu. what is the point of having the Search Button at the bottom?. seems repetitive and would clean up the UI if you removed it.

**Describe alternatives you've considered**
none. there is no setting in the Settings to hide or remove this button.

**Additional context**
![IMG_1102](https://user-images.githubusercontent.com/7124598/131966918-41c46ec8-41d0-4f82-a383-87127184b281.PNG)

**Comment by tijme** [comment]
Hi @shane-anderson,

The reason for the search button at the bottom is so that the app can be used one-handed most of the time. By using the search button at the bottom you don't have to reach all the way up to the screen.

Instead, I can remove the top search bar and make it show whenever you tap the bottom search button. This is currently requested in https://github.com/raivo-otp/ios-application/issues/29.
