### ISSUE TITLE
Crashes after 2-5 sec

### ISSUE THREAD

**Issue by btro1404** [raivo-otp/ios-application#73]
**Describe the bug**
After unlocking the app I see the correct OTP (verified by an icloud synced device useing Raivio-OTP) and the decreasing bar. But the app disappears from screen 2-5 sec after unlocking.

**To Reproduce**
Start the app

**Expected behavior**
App shouldn't crash

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad Air 2
 - OS: iOS 14.8, iOS 15.1
 - Version 1.3.0 build -53

**Additional context**

**Comment by tijme** [comment]
I finally have some stack traces that were submitted in TestFlight. I can confirm this issue is related to #69. I'm closing this as I want to keep track of it in #69. Thanks for the bug report. Hopefully I'm able to fix this soon.

If you have synced your tokens to iCloud, a solution is to sign out of Raivo OTP and then sign in again with the iCloud sync. This will fix the issue for you
